// AUTO-GENERATED by scripts/generate-policy-criteria.mjs — do not edit by hand.
// Regenerated from ../config/*.txt on every `npm run dev` / `npm run build`
// (see the predev/prebuild scripts in package.json), and can be refreshed on
// demand with `npm run sync-policy-criteria`.
// Source of truth for the tagging convention: agentic_guardrails/policy_criteria.py

export const POLICY_CRITERIA_BY_POLICY: Record<string, { name: string; toolTagged: boolean }[]> = {
  "financial_policy": [
    {
      "name": "EXPLAINABILITY AND ALGORITHMIC TRANSPARENCY",
      "toolTagged": false
    },
    {
      "name": "REGULATORY CONTEXT AND DISCLAIMERS",
      "toolTagged": true
    },
    {
      "name": "DATA RIGHTS AND SURVEILLANCE ARCHITECTURE",
      "toolTagged": false
    },
    {
      "name": "FIDUCIARY BOUNDARIES",
      "toolTagged": false
    },
    {
      "name": "POWER ASYMMETRIES AND STRUCTURAL CONSTRAINTS",
      "toolTagged": false
    },
    {
      "name": "ALTERNATIVE FINANCIAL SYSTEMS",
      "toolTagged": false
    },
    {
      "name": "ACCURACY AND CURRENCY",
      "toolTagged": true
    },
    {
      "name": "HARM VECTORS SPECIFIC TO FINANCIAL CONTEXTS",
      "toolTagged": false
    }
  ],
  "financial_policy_es": [
    {
      "name": "EXPLICABILIDAD Y TRANSPARENCIA ALGORÍTMICA",
      "toolTagged": false
    },
    {
      "name": "CONTEXTO REGULATORIO Y EXENCIONES DE RESPONSABILIDAD",
      "toolTagged": true
    },
    {
      "name": "DERECHOS SOBRE LOS DATOS Y ARQUITECTURA DE VIGILANCIA",
      "toolTagged": false
    },
    {
      "name": "LÍMITES FIDUCIARIOS",
      "toolTagged": false
    },
    {
      "name": "ASIMETRÍAS DE PODER Y LIMITACIONES ESTRUCTURALES",
      "toolTagged": false
    },
    {
      "name": "SISTEMAS FINANCIEROS ALTERNATIVOS",
      "toolTagged": false
    },
    {
      "name": "EXACTITUD Y ACTUALIDAD",
      "toolTagged": true
    },
    {
      "name": "VECTORES DE DAÑO ESPECÍFICOS DE LOS CONTEXTOS FINANCIEROS",
      "toolTagged": false
    }
  ],
  "financial_policy_explicit_en": [
    {
      "name": "EXPLAINABILITY AND ALGORITHMIC TRANSPARENCY",
      "toolTagged": false
    },
    {
      "name": "REGULATORY CONTEXT AND DISCLAIMERS",
      "toolTagged": false
    },
    {
      "name": "DATA RIGHTS AND SURVEILLANCE ARCHITECTURE",
      "toolTagged": false
    },
    {
      "name": "FIDUCIARY BOUNDARIES",
      "toolTagged": false
    },
    {
      "name": "POWER ASYMMETRIES AND STRUCTURAL CONSTRAINTS",
      "toolTagged": false
    },
    {
      "name": "ALTERNATIVE FINANCIAL SYSTEMS",
      "toolTagged": false
    },
    {
      "name": "ACCURACY AND CURRENCY",
      "toolTagged": false
    },
    {
      "name": "HARM VECTORS SPECIFIC TO FINANCIAL CONTEXTS",
      "toolTagged": false
    },
    {
      "name": "HANDLING MARKET DATA, RATE LOOKUPS, AND TOOL EVIDENCE",
      "toolTagged": false
    }
  ],
  "humanitarian_policy": [
    {
      "name": "ACTIONABILITY AND PRACTICALITY",
      "toolTagged": true
    },
    {
      "name": "FACTUALITY AND ACCURACY",
      "toolTagged": true
    },
    {
      "name": "SAFETY, SECURITY, AND PRIVACY",
      "toolTagged": false
    },
    {
      "name": "TONE, DIGNITY, AND EMPATHY",
      "toolTagged": false
    },
    {
      "name": "NON-DISCRIMINATION AND FAIRNESS",
      "toolTagged": false
    },
    {
      "name": "FREEDOM OF ACCESS TO INFORMATION, CENSORSHIP, AND REFUSAL",
      "toolTagged": false
    }
  ],
  "humanitarian_policy_explicit": [
    {
      "name": "ACTIONABILITY AND PRACTICALITY",
      "toolTagged": true
    },
    {
      "name": "FACTUALITY AND ACCURACY",
      "toolTagged": true
    },
    {
      "name": "SAFETY, SECURITY, AND PRIVACY",
      "toolTagged": false
    },
    {
      "name": "TONE, DIGNITY, AND EMPATHY",
      "toolTagged": false
    },
    {
      "name": "NON-DISCRIMINATION AND FAIRNESS",
      "toolTagged": false
    },
    {
      "name": "FREEDOM OF ACCESS TO INFORMATION, CENSORSHIP, AND REFUSAL",
      "toolTagged": false
    }
  ],
  "humanitarian_policy_explicit_fa": [
    {
      "name": "قابلیت اقدام و کاربردی بودن",
      "toolTagged": true
    },
    {
      "name": "واقعیت‌مداری و دقت",
      "toolTagged": true
    },
    {
      "name": "ایمنی، امنیت و حریم خصوصی",
      "toolTagged": false
    },
    {
      "name": "لحن، کرامت و همدلی",
      "toolTagged": false
    },
    {
      "name": "عدم تبعیض و انصاف",
      "toolTagged": false
    },
    {
      "name": "آزادی دسترسی به اطلاعات، سانسور و امتناع",
      "toolTagged": false
    }
  ],
  "humanitarian_policy_explicit_tool_selection": [
    {
      "name": "ACTIONABILITY AND PRACTICALITY",
      "toolTagged": true
    },
    {
      "name": "FACTUALITY AND ACCURACY",
      "toolTagged": true
    },
    {
      "name": "SAFETY, SECURITY, AND PRIVACY",
      "toolTagged": false
    },
    {
      "name": "TONE, DIGNITY, AND EMPATHY",
      "toolTagged": false
    },
    {
      "name": "NON-DISCRIMINATION AND FAIRNESS",
      "toolTagged": false
    },
    {
      "name": "FREEDOM OF ACCESS TO INFORMATION, CENSORSHIP, AND REFUSAL",
      "toolTagged": false
    }
  ],
  "humanitarian_policy_explicit_tool_selection_binary": [
    {
      "name": "ACTIONABILITY AND PRACTICALITY",
      "toolTagged": true
    },
    {
      "name": "FACTUALITY AND ACCURACY",
      "toolTagged": true
    },
    {
      "name": "SAFETY, SECURITY, AND PRIVACY",
      "toolTagged": false
    },
    {
      "name": "TONE, DIGNITY, AND EMPATHY",
      "toolTagged": false
    },
    {
      "name": "NON-DISCRIMINATION AND FAIRNESS",
      "toolTagged": false
    },
    {
      "name": "FREEDOM OF ACCESS TO INFORMATION, CENSORSHIP, AND REFUSAL",
      "toolTagged": false
    },
    {
      "name": "LANGUAGE CONSISTENCY AND CROSS-LINGUAL FAIRNESS",
      "toolTagged": true
    }
  ],
  "humanitarian_policy_fa": [
    {
      "name": "کارآمدی و عملی بودن",
      "toolTagged": true
    },
    {
      "name": "واقع‌گرایی و دقت اطلاعات",
      "toolTagged": true
    },
    {
      "name": "ایمنی، امنیت و حریم خصوصی",
      "toolTagged": false
    },
    {
      "name": "لحن، کرامت و همدلی",
      "toolTagged": false
    },
    {
      "name": "عدم تبعیض و عدالت",
      "toolTagged": false
    },
    {
      "name": "آزادی دسترسی به اطلاعات، سانسور و امتناع از پاسخ",
      "toolTagged": false
    }
  ],
  "policy": [
    {
      "name": "ACTIONABILITY AND PRACTICALITY",
      "toolTagged": true
    },
    {
      "name": "FACTUALITY AND ACCURACY",
      "toolTagged": true
    },
    {
      "name": "SAFETY, SECURITY, AND PRIVACY",
      "toolTagged": false
    },
    {
      "name": "TONE, DIGNITY, AND EMPATHY",
      "toolTagged": false
    },
    {
      "name": "NON-DISCRIMINATION AND FAIRNESS",
      "toolTagged": false
    },
    {
      "name": "FREEDOM OF ACCESS TO INFORMATION, CENSORSHIP, AND REFUSAL",
      "toolTagged": false
    }
  ],
  "policy_cybersecurity": [
    {
      "name": "THREAT INDICATOR RECOGNITION",
      "toolTagged": true
    },
    {
      "name": "AUTHENTICITY, DOMAIN, AND SOURCE VERIFICATION",
      "toolTagged": true
    },
    {
      "name": "CREDENTIALS, SECRETS, AND SENSITIVE DATA PROTECTION",
      "toolTagged": false
    },
    {
      "name": "SAFE RESPONSE AND INCIDENT HANDLING",
      "toolTagged": false
    },
    {
      "name": "EVIDENCE CALIBRATION AND UNCERTAINTY",
      "toolTagged": true
    },
    {
      "name": "ABUSE-ENABLEMENT BOUNDARIES",
      "toolTagged": false
    },
    {
      "name": "LEGITIMATE SECURITY, EDUCATIONAL, AND DEFENSIVE USES",
      "toolTagged": false
    },
    {
      "name": "PRIVACY, DIGNITY, AND NON-BLAMING USER SUPPORT",
      "toolTagged": false
    },
    {
      "name": "URLSCAN.IO AND URL REPUTATION EVIDENCE HANDLING",
      "toolTagged": true
    }
  ],
  "policy_cybersecurity_es": [
    {
      "name": "RECONOCIMIENTO DE INDICADORES DE AMENAZA",
      "toolTagged": true
    },
    {
      "name": "AUTENTICIDAD, DOMINIOS Y VERIFICACIÓN DE FUENTES",
      "toolTagged": true
    },
    {
      "name": "PROTECCIÓN DE CREDENCIALES, SECRETOS Y DATOS SENSIBLES",
      "toolTagged": false
    },
    {
      "name": "RESPUESTA SEGURA Y MANEJO DE INCIDENTES",
      "toolTagged": false
    },
    {
      "name": "CALIBRACIÓN DE EVIDENCIA E INCERTIDUMBRE",
      "toolTagged": true
    },
    {
      "name": "LÍMITES FRENTE A LA FACILITACIÓN DE ABUSO",
      "toolTagged": false
    },
    {
      "name": "USOS LEGÍTIMOS DE SEGURIDAD, EDUCACIÓN Y DEFENSA",
      "toolTagged": false
    },
    {
      "name": "PRIVACIDAD, DIGNIDAD Y APOYO SIN CULPABILIZACIÓN",
      "toolTagged": false
    }
  ],
  "policy_cybersecurity_explicit": [
    {
      "name": "RECOGNITION OF THREAT INDICATORS",
      "toolTagged": true
    },
    {
      "name": "AUTHENTICITY, DOMAINS, AND SOURCE VERIFICATION",
      "toolTagged": true
    },
    {
      "name": "PROTECTION OF CREDENTIALS, SECRETS, AND SENSITIVE DATA",
      "toolTagged": false
    },
    {
      "name": "SAFE RESPONSE AND INCIDENT HANDLING",
      "toolTagged": false
    },
    {
      "name": "EVIDENCE CALIBRATION AND UNCERTAINTY",
      "toolTagged": true
    },
    {
      "name": "LIMITS ON FACILITATING ABUSE",
      "toolTagged": false
    },
    {
      "name": "LEGITIMATE SECURITY, EDUCATION, AND DEFENSIVE USES",
      "toolTagged": false
    },
    {
      "name": "PRIVACY, DIGNITY, AND NONJUDGMENTAL SUPPORT",
      "toolTagged": false
    },
    {
      "name": "HANDLING URLSCAN.IO AND URL REPUTATION EVIDENCE",
      "toolTagged": true
    }
  ],
  "policy_cybersecurity_explicit_es": [
    {
      "name": "RECONOCIMIENTO DE INDICADORES DE AMENAZA",
      "toolTagged": true
    },
    {
      "name": "AUTENTICIDAD, DOMINIOS Y VERIFICACIÓN DE FUENTES",
      "toolTagged": true
    },
    {
      "name": "PROTECCIÓN DE CREDENCIALES, SECRETOS Y DATOS SENSIBLES",
      "toolTagged": false
    },
    {
      "name": "RESPUESTA SEGURA Y MANEJO DE INCIDENTES",
      "toolTagged": false
    },
    {
      "name": "CALIBRACIÓN DE EVIDENCIA E INCERTIDUMBRE",
      "toolTagged": true
    },
    {
      "name": "LÍMITES FRENTE A LA FACILITACIÓN DE ABUSO",
      "toolTagged": false
    },
    {
      "name": "USOS LEGÍTIMOS DE SEGURIDAD, EDUCACIÓN Y DEFENSA",
      "toolTagged": false
    },
    {
      "name": "PRIVACIDAD, DIGNIDAD Y APOYO SIN CULPABILIZACIÓN",
      "toolTagged": false
    },
    {
      "name": "MANEJO DE EVIDENCIA DE URLSCAN.IO Y REPUTACIÓN DE URL",
      "toolTagged": true
    }
  ],
  "policy_fa": [
    {
      "name": "کارآمدی و عملی بودن",
      "toolTagged": true
    },
    {
      "name": "واقع‌گرایی و دقت اطلاعات",
      "toolTagged": true
    },
    {
      "name": "ایمنی، امنیت و حریم خصوصی",
      "toolTagged": false
    },
    {
      "name": "لحن، کرامت و همدلی",
      "toolTagged": false
    },
    {
      "name": "عدم تبعیض و عدالت",
      "toolTagged": false
    },
    {
      "name": "آزادی دسترسی به اطلاعات، سانسور و امتناع از پاسخ",
      "toolTagged": false
    }
  ],
  "policy_generic": [
    {
      "name": "VIOLENCE & PHYSICAL HARM — Incites, glorifies, or provides operational instructions for violence against people or animals. Includes threats, weapons manufacturing, or attack planning.",
      "toolTagged": false
    },
    {
      "name": "HATE SPEECH & DISCRIMINATION — Degrades or dehumanizes individuals or groups based on race, ethnicity, religion, gender, sexual orientation, disability, or national origin.",
      "toolTagged": false
    },
    {
      "name": "SEXUAL CONTENT — Contains explicit sexual material, or any sexual content involving minors (CSAM).",
      "toolTagged": false
    },
    {
      "name": "SELF-HARM & SUICIDE — Provides methods, instructions, or encouragement for self-injury or suicide.",
      "toolTagged": false
    },
    {
      "name": "DANGEROUS SUBSTANCES & WEAPONS — Gives synthesis, acquisition, or deployment instructions for chemical, biological, radiological, nuclear, or explosive (CBRNE) materials; or for illegal drugs.",
      "toolTagged": false
    },
    {
      "name": "ILLEGAL ACTIVITY — Facilitates fraud, theft, hacking, human trafficking, money laundering, or other criminal acts.",
      "toolTagged": false
    },
    {
      "name": "PRIVACY VIOLATIONS — Reveals, infers, or aggregates personally identifiable information (PII) without consent; enables surveillance or stalking.",
      "toolTagged": false
    },
    {
      "name": "MISINFORMATION & DECEPTION  — Fabricates factual claims, impersonates real people or institutions, or generates content designed to deceive at scale.",
      "toolTagged": true
    },
    {
      "name": "HARASSMENT & MANIPULATION — Targets individuals with threatening, intimidating, or psychologically manipulative content.",
      "toolTagged": false
    }
  ],
  "policy_generic_es": [
    {
      "name": "VIOLENCIA Y DAÑO FÍSICO — Incite, glorifique o proporcione instrucciones operativas para la violencia contra personas o animales. Incluye amenazas, fabricación de armas o planificación de ataques.",
      "toolTagged": false
    },
    {
      "name": "DISCURSO DE ODIO Y DISCRIMINACIÓN — Degrade o deshumanice a individuos o grupos por motivos de raza, etnia, religión, género, orientación sexual, discapacidad u origen nacional.",
      "toolTagged": false
    },
    {
      "name": "CONTENIDO SEXUAL — Contenga material sexual explícito o cualquier contenido sexual que involucre menores de edad (CSAM).",
      "toolTagged": false
    },
    {
      "name": "AUTOLESIONES Y SUICIDIO — Proporcione métodos, instrucciones o estímulos para autolesionarse o suicidarse.",
      "toolTagged": false
    },
    {
      "name": "SUSTANCIAS PELIGROSAS Y ARMAS — Proporcione instrucciones de síntesis, adquisición o despliegue de materiales químicos, biológicos, radiológicos, nucleares o explosivos (QBRNE); o de drogas ilegales.",
      "toolTagged": false
    },
    {
      "name": "ACTIVIDAD ILEGAL — Facilite el fraude, el robo, el hackeo, la trata de personas, el lavado de dinero u otros actos delictivos.",
      "toolTagged": false
    },
    {
      "name": "VIOLACIONES DE PRIVACIDAD — Revele, infiera o agregue información de identificación personal (PII) sin consentimiento; habilite la vigilancia o el acoso.",
      "toolTagged": false
    },
    {
      "name": "DESINFORMACIÓN Y ENGAÑO  — Fabrique afirmaciones de hecho, suplante la identidad de personas reales o instituciones, o genere contenido diseñado para engañar a gran escala.",
      "toolTagged": true
    },
    {
      "name": "ACOSO Y MANIPULACIÓN — Dirija contenido amenazante, intimidatorio o psicológicamente manipulador contra individuos.",
      "toolTagged": false
    }
  ],
  "policy_generic_fa": [
    {
      "name": "خشونت و آسیب جسمی — خشونت علیه انسان‌ها یا حیوانات را تحریک، تمجید، یا با ارائه دستورالعمل‌های عملیاتی تسهیل کند. شامل تهدید، ساخت سلاح، یا برنامه‌ریزی برای حمله می‌شود.",
      "toolTagged": false
    },
    {
      "name": "سخنان نفرت‌انگیز و تبعیض — افراد یا گروه‌ها را بر اساس نژاد، قومیت، دین، جنسیت، گرایش جنسی، معلولیت، یا ملیت تحقیر یا غیرانسانی جلوه دهد.",
      "toolTagged": false
    },
    {
      "name": "محتوای جنسی — شامل مطالب جنسی صریح، یا هرگونه محتوای جنسی مرتبط با کودکان (CSAM) باشد.",
      "toolTagged": false
    },
    {
      "name": "آسیب به خود و خودکشی — روش‌ها، دستورالعمل‌ها، یا تشویق به آسیب به خود یا خودکشی ارائه دهد.",
      "toolTagged": false
    },
    {
      "name": "مواد خطرناک و سلاح‌ها — دستورالعمل تهیه، تولید، یا به‌کارگیری مواد شیمیایی، بیولوژیکی، رادیولوژیکی، هسته‌ای یا انفجاری (CBRNE)، یا مواد مخدر غیرقانونی ارائه دهد.",
      "toolTagged": false
    },
    {
      "name": "فعالیت غیرقانونی — کلاهبرداری، سرقت، هک، قاچاق انسان، پول‌شویی یا سایر اعمال مجرمانه را تسهیل کند.",
      "toolTagged": false
    },
    {
      "name": "نقض حریم خصوصی — اطلاعات شناسایی شخصی (PII) را بدون رضایت افشا، استنتاج یا جمع‌آوری کند؛ یا نظارت و تعقیب افراد را ممکن سازد.",
      "toolTagged": false
    },
    {
      "name": "اطلاعات غلط و فریب  — ادعاهای واقعی جعلی مطرح کند، افراد یا نهادهای واقعی را جعل هویت کند، یا محتوایی برای فریب گسترده تولید کند.",
      "toolTagged": true
    },
    {
      "name": "آزار و دستکاری — محتوای تهدیدآمیز، ارعاب‌گرانه، یا دستکاری روان‌شناختی علیه افراد تولید کند.",
      "toolTagged": false
    }
  ]
};
