import { POLICY_CRITERIA_BY_POLICY } from "@/lib/policyCriteria.generated";

/**
 * The canonical criterion list per POLICY FILE (not per use case — different
 * policy variants in the same domain can tag different criteria as needing
 * tools, e.g. humanitarian_policy_explicit_tool_selection_binary tags
 * LANGUAGE CONSISTENCY AND CROSS-LINGUAL FAIRNESS while a plain humanitarian
 * policy variant may not), straight from config/*.txt in the parent repo —
 * including which criteria are tagged "(potentially needs tool calls)".
 * This is the source of truth for "does this criterion require agentic tool
 * use", not the judge's own self-reported `tool_influenced` field
 * (scenario-dependent, not always populated) and not "is this criterion
 * present in the agentic pass's criteriaVerdicts" (many historical records
 * have an empty agentic array even for tool-tagged criteria — see
 * adapters/humanitarian.ts notes).
 *
 * POLICY_CRITERIA_BY_POLICY is generated by scripts/generate-policy-criteria.mjs
 * from the real policy files — see that script for how it stays in sync.
 * Previously this was a hand-maintained list keyed by use case, which
 * silently dropped an entire criterion for one humanitarian policy variant
 * (LANGUAGE CONSISTENCY AND CROSS-LINGUAL FAIRNESS was never added when that
 * criterion's tag was introduced) with nothing to catch the drift.
 */
export const POLICY_CRITERIA = POLICY_CRITERIA_BY_POLICY;

function criteriaFor(policyName: string): { name: string; toolTagged: boolean }[] {
  return POLICY_CRITERIA_BY_POLICY[policyName] ?? [];
}

/**
 * Maps a raw criterion name from judge output to its canonical form. Handles
 * the judge sometimes emitting a truncated name (observed in real data: e.g.
 * "FREEDOM OF ACCESS TO INFORMATION" for the full
 * "FREEDOM OF ACCESS TO INFORMATION, CENSORSHIP, AND REFUSAL") by matching on
 * prefix. Falls back to the trimmed raw name (visible as its own row) rather
 * than silently dropping anything unrecognized.
 */
export function normalizeCriterionName(policyName: string, raw: string): string {
  const trimmed = raw.trim();
  const canonical = criteriaFor(policyName);

  const exact = canonical.find((c) => c.name === trimmed);
  if (exact) return exact.name;

  const upper = trimmed.toUpperCase();
  const prefixMatch = canonical.find(
    (c) => c.name.toUpperCase().startsWith(upper) || upper.startsWith(c.name.toUpperCase())
  );
  if (prefixMatch) return prefixMatch.name;

  return trimmed;
}

export function isToolTaggedCriterion(policyName: string, canonicalName: string): boolean {
  return criteriaFor(policyName).some((c) => c.name === canonicalName && c.toolTagged);
}

export function toolTaggedCriteriaNames(policyName: string): string[] {
  return criteriaFor(policyName).filter((c) => c.toolTagged).map((c) => c.name);
}
